package com.chronosphere.neoforge.loot;

import com.chronosphere.Chronosphere;
import com.chronosphere.registry.ModItems;
import com.mojang.serialization.MapCodec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.parameters.LootContextParams;
import net.minecraft.world.level.storage.loot.predicates.LootItemCondition;
import net.neoforged.neoforge.common.loot.IGlobalLootModifier;
import net.neoforged.neoforge.common.loot.LootModifier;

/**
 * Global Loot Modifier that replaces Wheat Seeds with Time Wheat Seeds
 * when grass or ferns are broken in the Chronosphere dimension.
 *
 * This modifier:
 * 1. Checks if the loot was generated in the Chronosphere dimension
 * 2. Replaces any Wheat Seeds in the loot with Time Wheat Seeds
 *
 * Implementation: NeoForge-specific solution for grass/fern loot modification
 */
public class GrassTimeWheatSeedModifier extends LootModifier {
    public static final MapCodec<GrassTimeWheatSeedModifier> CODEC = RecordCodecBuilder.mapCodec(inst ->
        codecStart(inst).apply(inst, GrassTimeWheatSeedModifier::new)
    );

    private static final ResourceKey<Level> CHRONOSPHERE_DIMENSION =
        ResourceKey.create(Registries.DIMENSION,
            ResourceLocation.fromNamespaceAndPath(Chronosphere.MOD_ID, "chronosphere"));

    /**
     * Constructor for the loot modifier.
     *
     * @param conditions The conditions that must be met for this modifier to apply
     */
    public GrassTimeWheatSeedModifier(LootItemCondition[] conditions) {
        super(conditions);
    }

    /**
     * Apply the loot modification.
     * Replaces Wheat Seeds with Time Wheat Seeds in Chronosphere dimension.
     *
     * @param generatedLoot The loot that was generated by the loot table
     * @param context The loot context
     * @return Modified loot with Time Wheat Seeds instead of Wheat Seeds
     */
    @Override
    protected ObjectArrayList<ItemStack> doApply(ObjectArrayList<ItemStack> generatedLoot, LootContext context) {
        // Check if we're in the Chronosphere dimension
        Level level = context.getLevel();
        if (level.dimension() != CHRONOSPHERE_DIMENSION) {
            return generatedLoot;
        }

        // Replace Wheat Seeds with Time Wheat Seeds
        ObjectArrayList<ItemStack> modifiedLoot = new ObjectArrayList<>();
        for (ItemStack stack : generatedLoot) {
            if (stack.is(Items.WHEAT_SEEDS)) {
                // Replace with Time Wheat Seeds, keeping the same count
                ItemStack timeWheatSeeds = new ItemStack(ModItems.TIME_WHEAT_SEEDS.get(), stack.getCount());
                modifiedLoot.add(timeWheatSeeds);
            } else {
                modifiedLoot.add(stack);
            }
        }

        return modifiedLoot;
    }

    @Override
    public MapCodec<? extends IGlobalLootModifier> codec() {
        return CODEC;
    }
}
