package com.chronodawn.gametest;

import com.chronodawn.registry.ModItems;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.chat.Component;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.GameType;

import java.util.function.Consumer;

/**
 * Common GameTest logic shared between Fabric and NeoForge implementations.
 *
 * Contains player input tests that require complex setup and are kept as
 * individual test methods. Registry-driven tests (blocks, entities, tools,
 * armor, attributes) are generated by {@link RegistryDrivenTestGenerator}.
 *
 * Reference: T172f/T173d - Common GameTest Logic
 */
public final class ChronoDawnGameTestLogic {

    private ChronoDawnGameTestLogic() {
        // Utility class
    }

    // Standard test position
    public static final BlockPos TEST_POS = new BlockPos(1, 2, 1);

    // ============== Player Input Tests ==============

    /**
     * Test that a mock player can be created in the game test environment.
     */
    public static final Consumer<GameTestHelper> TEST_MOCK_PLAYER_CAN_BE_CREATED = helper -> {
        helper.runAfterDelay(1, () -> {
            try {
                Player player = helper.makeMockPlayer(GameType.SURVIVAL);
                if (player != null) {
                    helper.succeed();
                } else {
                    helper.fail(Component.literal("Mock player was null"));
                }
            } catch (Exception e) {
                helper.fail(Component.literal("Failed to create mock player: " + e.getMessage()));
            }
        });
    };

    /**
     * Test that a mock player can be equipped with armor in the chest slot.
     */
    public static final Consumer<GameTestHelper> TEST_PLAYER_CAN_EQUIP_CHESTPLATE = helper -> {
        helper.runAfterDelay(1, () -> {
            try {
                Player player = helper.makeMockPlayer(GameType.SURVIVAL);
                ItemStack chestplate = new ItemStack(ModItems.CLOCKSTONE_CHESTPLATE.get());

                player.setItemSlot(EquipmentSlot.CHEST, chestplate);

                ItemStack equipped = player.getItemBySlot(EquipmentSlot.CHEST);
                if (!equipped.isEmpty() && equipped.getItem() == ModItems.CLOCKSTONE_CHESTPLATE.get()) {
                    helper.succeed();
                } else {
                    helper.fail(Component.literal("Chestplate was not properly equipped"));
                }
            } catch (Exception e) {
                helper.fail(Component.literal("Failed to equip chestplate: " + e.getMessage()));
            }
        });
    };

    /**
     * Test that Time Tyrant's Mail can be equipped in the chest slot.
     */
    public static final Consumer<GameTestHelper> TEST_TIME_TYRANT_MAIL_CAN_BE_EQUIPPED = helper -> {
        helper.runAfterDelay(1, () -> {
            try {
                Player player = helper.makeMockPlayer(GameType.SURVIVAL);
                ItemStack mail = new ItemStack(ModItems.TIME_TYRANT_MAIL.get());

                player.setItemSlot(EquipmentSlot.CHEST, mail);

                ItemStack equipped = player.getItemBySlot(EquipmentSlot.CHEST);
                if (!equipped.isEmpty() && equipped.getItem() == ModItems.TIME_TYRANT_MAIL.get()) {
                    helper.succeed();
                } else {
                    helper.fail(Component.literal("Time Tyrant's Mail was not properly equipped in chest slot"));
                }
            } catch (Exception e) {
                helper.fail(Component.literal("Failed to equip Time Tyrant's Mail: " + e.getMessage()));
            }
        });
    };

    /**
     * Test that player can hold Chronoblade in main hand.
     */
    public static final Consumer<GameTestHelper> TEST_PLAYER_CAN_HOLD_CHRONOBLADE = helper -> {
        helper.runAfterDelay(1, () -> {
            try {
                Player player = helper.makeMockPlayer(GameType.SURVIVAL);
                ItemStack chronoblade = new ItemStack(ModItems.CHRONOBLADE.get());

                player.setItemSlot(EquipmentSlot.MAINHAND, chronoblade);

                ItemStack equipped = player.getItemBySlot(EquipmentSlot.MAINHAND);
                if (!equipped.isEmpty() && equipped.getItem() == ModItems.CHRONOBLADE.get()) {
                    helper.succeed();
                } else {
                    helper.fail(Component.literal("Chronoblade was not properly equipped in main hand"));
                }
            } catch (Exception e) {
                helper.fail(Component.literal("Failed to equip Chronoblade: " + e.getMessage()));
            }
        });
    };

    /**
     * Test that player can be equipped with full Clockstone armor set.
     */
    public static final Consumer<GameTestHelper> TEST_PLAYER_CAN_EQUIP_FULL_ARMOR_SET = helper -> {
        helper.runAfterDelay(1, () -> {
            try {
                Player player = helper.makeMockPlayer(GameType.SURVIVAL);

                ItemStack helmet = new ItemStack(ModItems.CLOCKSTONE_HELMET.get());
                ItemStack chestplate = new ItemStack(ModItems.CLOCKSTONE_CHESTPLATE.get());
                ItemStack leggings = new ItemStack(ModItems.CLOCKSTONE_LEGGINGS.get());
                ItemStack boots = new ItemStack(ModItems.CLOCKSTONE_BOOTS.get());

                player.setItemSlot(EquipmentSlot.HEAD, helmet);
                player.setItemSlot(EquipmentSlot.CHEST, chestplate);
                player.setItemSlot(EquipmentSlot.LEGS, leggings);
                player.setItemSlot(EquipmentSlot.FEET, boots);

                boolean helmetEquipped = player.getItemBySlot(EquipmentSlot.HEAD).getItem() == ModItems.CLOCKSTONE_HELMET.get();
                boolean chestplateEquipped = player.getItemBySlot(EquipmentSlot.CHEST).getItem() == ModItems.CLOCKSTONE_CHESTPLATE.get();
                boolean leggingsEquipped = player.getItemBySlot(EquipmentSlot.LEGS).getItem() == ModItems.CLOCKSTONE_LEGGINGS.get();
                boolean bootsEquipped = player.getItemBySlot(EquipmentSlot.FEET).getItem() == ModItems.CLOCKSTONE_BOOTS.get();

                if (helmetEquipped && chestplateEquipped && leggingsEquipped && bootsEquipped) {
                    helper.succeed();
                } else {
                    helper.fail(Component.literal("Not all armor pieces were properly equipped: helmet=" + helmetEquipped +
                        ", chestplate=" + chestplateEquipped + ", leggings=" + leggingsEquipped +
                        ", boots=" + bootsEquipped));
                }
            } catch (Exception e) {
                helper.fail(Component.literal("Failed to equip full armor set: " + e.getMessage()));
            }
        });
    };

    /**
     * Test that player inventory can receive items.
     */
    public static final Consumer<GameTestHelper> TEST_PLAYER_INVENTORY_CAN_RECEIVE_ITEMS = helper -> {
        helper.runAfterDelay(1, () -> {
            try {
                Player player = helper.makeMockPlayer(GameType.SURVIVAL);
                ItemStack timeCrystal = new ItemStack(ModItems.TIME_CRYSTAL.get(), 10);

                boolean added = player.getInventory().add(timeCrystal);

                if (added) {
                    boolean hasItems = player.getInventory().contains(new ItemStack(ModItems.TIME_CRYSTAL.get()));
                    if (hasItems) {
                        helper.succeed();
                    } else {
                        helper.fail(Component.literal("Items were added but not found in inventory"));
                    }
                } else {
                    helper.fail(Component.literal("Failed to add items to player inventory"));
                }
            } catch (Exception e) {
                helper.fail(Component.literal("Failed to manipulate player inventory: " + e.getMessage()));
            }
        });
    };
}
